-- MySQL Script generated by MySQL Workbench
-- Mon Feb 27 13:06:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tumedianaranja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tumedianaranja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tumedianaranja` DEFAULT CHARACTER SET utf8 ;
USE `tumedianaranja` ;

-- -----------------------------------------------------
-- Table `tumedianaranja`.`campana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tumedianaranja`.`campana` (
  `id_campana` INT NOT NULL,
  `nombre_campana` VARCHAR(50) NOT NULL,
  `fecha_inicio_campana` DATE NOT NULL,
  `fecha_fin_campana` DATE NULL DEFAULT NULL,
  `estatus_campana` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_campana`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tumedianaranja`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tumedianaranja`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `rut_empresa` VARCHAR(20) NOT NULL,
  `razon_social` VARCHAR(100) NOT NULL,
  `telefono_empresa` VARCHAR(50) NOT NULL,
  `telefono2_empresa` VARCHAR(12) CHARACTER SET 'utf8' NOT NULL,
  `rubro_economico` VARCHAR(100) NOT NULL,
  `sub_rubro_economico` VARCHAR(100) NOT NULL,
  `actividad_economica` VARCHAR(100) NOT NULL,
  `tamano_empresa` VARCHAR(50) NOT NULL,
  `fecha_inicio_actividad` DATE NOT NULL,
  `cantidad_trabajadores` INT(4) NOT NULL,
  `competencia` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `comuna` VARCHAR(50) NOT NULL,
  `provincia` VARCHAR(50) NOT NULL,
  `region` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`rut_empresa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tumedianaranja`.`tipificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tumedianaranja`.`tipificacion` (
  `id_tipificacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_tipificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tumedianaranja`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tumedianaranja`.`contacto` (
  `id_contacto` INT NOT NULL AUTO_INCREMENT,
  `nombre_apellido_contacto` VARCHAR(50) NOT NULL,
  `telefono_fijo_contacto` INT(20) NOT NULL,
  `telefono_movil_contacto` INT(20) NOT NULL,
  `mail_contacto` VARCHAR(50) NOT NULL,
  `nivel_decision` VARCHAR(50) NOT NULL,
  `area_decision` VARCHAR(50) NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `rut_empresa` VARCHAR(20) NULL,
  `id_tipificacion` INT NULL,
  PRIMARY KEY (`id_contacto`),
  CONSTRAINT `rut_empresa`
    FOREIGN KEY (`rut_empresa`)
    REFERENCES `tumedianaranja`.`empresa` (`rut_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tipificacion`
    FOREIGN KEY (`id_tipificacion`)
    REFERENCES `tumedianaranja`.`tipificacion` (`id_tipificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `rut_empresa_idx` ON `tumedianaranja`.`contacto` (`rut_empresa` ASC) VISIBLE;

CREATE INDEX `id_tipificacion_idx` ON `tumedianaranja`.`contacto` (`id_tipificacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tumedianaranja`.`ejecutivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tumedianaranja`.`ejecutivo` (
  `id_matricula_ejecutivo` INT NOT NULL AUTO_INCREMENT,
  `nombre_ejecutivo` VARCHAR(50) NOT NULL,
  `apellido_ejecutivo` VARCHAR(50) NOT NULL,
  `mail_ejecutivo` VARCHAR(100) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `sesion` VARCHAR(1) NOT NULL,
  `hora_inicio_labor` TIME NOT NULL,
  `hora_fin_labor` TIME NOT NULL,
  PRIMARY KEY (`id_matricula_ejecutivo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tumedianaranja`.`ejecutivo_campana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tumedianaranja`.`ejecutivo_campana` (
  `id_ejecutivo_campana` INT NOT NULL AUTO_INCREMENT,
  `id_matricula_ejecutivo` INT NOT NULL,
  `id_campana` INT NOT NULL,
  PRIMARY KEY (`id_ejecutivo_campana`),
  CONSTRAINT `id_campana`
    FOREIGN KEY (`id_campana`)
    REFERENCES `tumedianaranja`.`campana` (`id_campana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_matricula_ejecutivo`
    FOREIGN KEY (`id_matricula_ejecutivo`)
    REFERENCES `tumedianaranja`.`ejecutivo` (`id_matricula_ejecutivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `id_campana_idx` ON `tumedianaranja`.`ejecutivo_campana` (`id_campana` ASC) VISIBLE;

CREATE INDEX `id_matricula_ejecutivo_idx` ON `tumedianaranja`.`ejecutivo_campana` (`id_matricula_ejecutivo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tumedianaranja`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tumedianaranja`.`agenda` (
  `id_agenda` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `id_matricula_ejecutivo` INT NULL,
  PRIMARY KEY (`id_agenda`),
  CONSTRAINT `id_matricula_ejecutivo`
    FOREIGN KEY (`id_matricula_ejecutivo`)
    REFERENCES `tumedianaranja`.`ejecutivo` (`id_matricula_ejecutivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_matricula_ejecutivo_idx` ON `tumedianaranja`.`agenda` (`id_matricula_ejecutivo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tumedianaranja`.`empresa_campana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tumedianaranja`.`empresa_campana` (
  `id_empresa_campana` INT NOT NULL AUTO_INCREMENT,
  `rut_empresa` VARCHAR(20) NOT NULL,
  `id_campana` INT NOT NULL,
  `comentario` VARCHAR(1000) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `id_agenda` INT NULL,
  PRIMARY KEY (`id_empresa_campana`),
  CONSTRAINT `id_campana`
    FOREIGN KEY (`id_campana`)
    REFERENCES `tumedianaranja`.`campana` (`id_campana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rut_empresa`
    FOREIGN KEY (`rut_empresa`)
    REFERENCES `tumedianaranja`.`empresa` (`rut_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_agenda`
    FOREIGN KEY (`id_agenda`)
    REFERENCES `tumedianaranja`.`agenda` (`id_agenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `id_campana_idx` ON `tumedianaranja`.`empresa_campana` (`id_campana` ASC) VISIBLE;

CREATE INDEX `rut_empresa_idx` ON `tumedianaranja`.`empresa_campana` (`rut_empresa` ASC) VISIBLE;

CREATE INDEX `id_agenda_idx` ON `tumedianaranja`.`empresa_campana` (`id_agenda` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
